# nginx/nginx.conf

# Bloque requerido por nginx para configuracion de conexiones
events {}

http {
    # 1. Definimos nuestro sistema backend (Django + Gunicorn)
    # El nombre 'web' debe coincidir con el nombre del servicio en docker-compose
    upstream django_backend {
        server web:8000;
    }
    upstream flask_v2 {
        server pagos_flask:5000;
    }
    
    server {
        # Nginx escuchara en el puerto web estandar (80)
        listen 80;

        # Ignorar logs de favicon para no saturar el servidor
        location = /favicon.ico { access_log off; log_not_found off; }

        # RUTA VIEJA : Sigue yendo a Django
        location /api/v1/ {
        proxy_pass http://django_v1;
        proxy_set_header Host $host;
        }

        # RUTA NUEVA : Estrangulamos la funcion de compra y la mandamos a
        Flask
        location /api/v2/comprar {
        proxy_pass http://flask_v2;
        proxy_set_header Host $host;
        }
    }
}