# nginx/nginx.conf
events {}
http {
    upstream django_backend {
        server web:8000;
    }
    upstream flask_v2 {
        server pagos_flask:5000;
    }

    server {
        listen 80;
        location = /favicon.ico { access_log off; log_not_found off; }

        # RUTA VIEJA: sigue yendo a Django
        location /api/v1/ {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
        }

        # RUTA NUEVA: va a Flask
        location /api/v2/comprar {
            proxy_pass http://flask_v2;
            proxy_set_header Host $host;
        }
    }
}